project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left: 
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1: Programming Elegant DataVis with ggplot2"
          href: Hands-on_Ex/Hands-on_Ex01.html
        - text: "Hands-on Exercise 2: Beyond ggplot2 Fundamentals"
          href: Hands-on_Ex/Hands-on_Ex02.html
        - text: "Hands-on Exercise 3: Programming Interactive Data Visualisation with R"
          href: Hands-on_Ex/Hands-on_Ex03.html
        - text: "Hands-on Exercise 4.1: Visual Statistical Analysis"
          href: Hands-on_Ex/Hands-on_Ex04.1.html
        - text: "Hands-on Exercise 4.2: Visualising Uncertainty"
          href: Hands-on_Ex/Hands-on_Ex04.2.html
        - text: "Hands-on Exercise 4.3: Building Funnel Plot with R"
          href: Hands-on_Ex/Hands-on_Ex04.3.html
        - text: "Hands-on Exercise 5.1: Building Ternary Plot with R"
          href: Hands-on_Ex/Hands-on_Ex05.1.html
        - text: "Hands-on Exercise 5.2: Visualising Correlation Matrices"
          href: Hands-on_Ex/Hands-on_Ex05.2.html
        - text: "Hands-on Exercise 5.3: Building Heatmap for Visualising and Analysing Multivariate Data"
          href: Hands-on_Ex/Hands-on_Ex05.3.html
        - text: "Hands-on Exercise 5.4: Creating Parallel Coordinates Plots with R"
          href: Hands-on_Ex/Hands-on_Ex05.4.html
        - text: "Hands-on Exercise 6: Visualising and Analysing Time-oriented Data"
          href: Hands-on_Ex/Hands-on_Ex06.html
        - text: "Hands-on Exercise 7.1: Choropleth Mapping with R"
          href: Hands-on_Ex/Hands-on_Ex07.1.html
        - text: "Hands-on Exercise 7.2: Visualising Geospatial Point Data"
          href: Hands-on_Ex/Hands-on_Ex07.2.html
        - text: "Hands-on Exercise 7.3: Analytical Mapping"
          href: Hands-on_Ex/Hands-on_Ex07.3.html
        - text: "Hands-on Exercise 8: Modelling, Visualising and Analysing Network Data with R"
          href: Hands-on_Ex/Hands-on_Ex08.html
        - text: "Hands-on Exercise 9: Information Dashboard Design: R methods"
          href: Hands-on_Ex/Hands-on_Ex09.html
        - text: "Hands-on Exercise 10: Financial Data Visualisation and Analysis"
          href: Hands-on_Ex/Hands-on_Ex10.html
    - text: "In-Class Exercises"
      menu:
        - text: "In-Class Exercise 3: Programming Interactive Data Visualisation with R"
          href: In-Class_Ex/In-Class_Ex03.html
        - text: "In-Class Exercise 4: Visual Statistical Analysis"
          href: In-Class_Ex/In-Class_Ex04.html
        - text: "In-Class Exercise 5: Creating Parallel Coordinates Plots with R"
          href: In-Class_Ex/In-Class_Ex05.html
        - text: "In-Class Exercise 6: Visualising and Analysing Time-oriented Data"
          href: In-Class_Ex/In-Class_Ex06.html
        - text: "In-Class Exercise 7: Analytical Mapping"
          href: In-Class_Ex/In-Class_Ex07.html
        - text: "In-Class Exercise 8: Modelling, Visualising and Analysing Network Data with R"
          href: In-Class_Ex/In-Class_Ex08.html
        - text: "In-Class Exercise 9: Information Dashboard Design: R methods"
          href: In-Class_Ex/In-Class_Ex09.html
        - text: "In-Class Exercise 10: Financial Data Visualisation and Analysis"
          href: In-Class_Ex/In-Class_Ex10.html
    - text: "Take-home Exercises"
      menu:
        - text: "Take-home Exercise 1: An Exploration on Singapore's 2022 Population through Age-Sex Pyramid"
          href: Take-home_Ex/Take-home_Ex01.html
        - text: "Take-home Exercise 2: Critique of Singapore Age-Sex Pyramid"
          href: Take-home_Ex/Take-home_Ex02.html
        - text: "Take-home Exercise 3: Putting Visual Analytics into Practical Use"
          href: Take-home_Ex/Take-home_Ex03.html
        - text: "Take-home Exercise 4: Putting Visual Analytics into Practical Use"
          href: Take-home_Ex/Take-home_Ex04.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

